[package]
name = "armalint"
version = "0.1.0"
authors = ["Brett <brett@bmandesigns.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "*"
pest_derive = "*"
regex = "*"
strum = "*"
strum_macros = "*"

[build-dependencies]
pest = "*"
pest_derive = "*"
